// Mocks generated by Mockito 5.4.6 from annotations
// in zync_gum/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:zync_gum/core/errors/failure.dart' as _i6;
import 'package:zync_gum/core/models/either/either.dart' as _i5;
import 'package:zync_gum/core/usecase/usecase.dart' as _i8;
import 'package:zync_gum/features/auth/domain/entities/auth_entity/auth_entity.dart'
    as _i7;
import 'package:zync_gum/features/auth/domain/repositories/auth_repositories.dart'
    as _i2;
import 'package:zync_gum/features/auth/domain/usecases/check_auth_usecase/check_auth_usecase.dart'
    as _i3;
import 'package:zync_gum/features/auth/domain/usecases/sign_in_email_usecase/sign_in_email_usecase.dart'
    as _i10;
import 'package:zync_gum/features/auth/domain/usecases/sign_in_google_usecase/sign_in_google_usecase.dart'
    as _i11;
import 'package:zync_gum/features/auth/domain/usecases/sign_out_usecase/sign_out_usecase.dart'
    as _i13;
import 'package:zync_gum/features/auth/domain/usecases/sign_up_email_usecase/sign_up_email_usecase.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthRepositories_0 extends _i1.SmartFake
    implements _i2.AuthRepositories {
  _FakeAuthRepositories_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CheckAuthUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckAuthUsecase extends _i1.Mock implements _i3.CheckAuthUsecase {
  MockCheckAuthUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.UserEntity?>> call(
    _i8.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, _i7.UserEntity?>>.value(
                  _i9.dummyValue<_i5.Either<_i6.Failure, _i7.UserEntity?>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.UserEntity?>>);
}

/// A class which mocks [SignInEmailUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInEmailUsecase extends _i1.Mock
    implements _i10.SignInEmailUsecase {
  MockSignInEmailUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.UserEntity>> call(
    _i10.SignInEmailParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, _i7.UserEntity>>.value(
                  _i9.dummyValue<_i5.Either<_i6.Failure, _i7.UserEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.UserEntity>>);
}

/// A class which mocks [SignInGoogleUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInGoogleUsecase extends _i1.Mock
    implements _i11.SignInGoogleUsecase {
  MockSignInGoogleUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.UserEntity>> call(
    _i8.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, _i7.UserEntity>>.value(
                  _i9.dummyValue<_i5.Either<_i6.Failure, _i7.UserEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.UserEntity>>);
}

/// A class which mocks [SignUpEmailUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpEmailUsecase extends _i1.Mock
    implements _i12.SignUpEmailUsecase {
  MockSignUpEmailUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.UserEntity>> call(
    _i12.SignUpEmailParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, _i7.UserEntity>>.value(
                  _i9.dummyValue<_i5.Either<_i6.Failure, _i7.UserEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.UserEntity>>);
}

/// A class which mocks [SignOutUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutUsecase extends _i1.Mock implements _i13.SignOutUsecase {
  MockSignOutUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i9.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);
}
