// Mocks generated by Mockito 5.4.6 from annotations
// in zync_gum/test/features/home/data/repositories/home_repositories_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zync_gum/core/errors/failure.dart' as _i5;
import 'package:zync_gum/core/models/either/either.dart' as _i4;
import 'package:zync_gum/features/home/data/data_source/home_data_source.dart'
    as _i2;
import 'package:zync_gum/features/home/data/models/business_response/business_response.dart'
    as _i8;
import 'package:zync_gum/features/home/data/models/inventory_response/inventory_response.dart'
    as _i7;
import 'package:zync_gum/features/home/data/models/production_line_response/production_line_response.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HomeDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeDataSource extends _i1.Mock implements _i2.HomeDataSource {
  MockHomeDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Either<_i5.Failure, List<_i6.ProductionLineResponse>>>
  watchProductionLines() =>
      (super.noSuchMethod(
            Invocation.method(#watchProductionLines, []),
            returnValue:
                _i3.Stream<
                  _i4.Either<_i5.Failure, List<_i6.ProductionLineResponse>>
                >.empty(),
          )
          as _i3.Stream<
            _i4.Either<_i5.Failure, List<_i6.ProductionLineResponse>>
          >);

  @override
  _i3.Stream<_i4.Either<_i5.Failure, List<_i7.InventoryResponse>>>
  watchInventory() =>
      (super.noSuchMethod(
            Invocation.method(#watchInventory, []),
            returnValue:
                _i3.Stream<
                  _i4.Either<_i5.Failure, List<_i7.InventoryResponse>>
                >.empty(),
          )
          as _i3.Stream<_i4.Either<_i5.Failure, List<_i7.InventoryResponse>>>);

  @override
  _i3.Stream<_i4.Either<_i5.Failure, List<_i8.BusinessResponse>>>
  watchBusinesses(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchBusinesses, [userId]),
            returnValue:
                _i3.Stream<
                  _i4.Either<_i5.Failure, List<_i8.BusinessResponse>>
                >.empty(),
          )
          as _i3.Stream<_i4.Either<_i5.Failure, List<_i8.BusinessResponse>>>);
}
