// Mocks generated by Mockito 5.4.6 from annotations
// in zync_gum/test/features/home/domain/usecases/get_production_lines_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zync_gum/core/errors/failure.dart' as _i5;
import 'package:zync_gum/core/models/either/either.dart' as _i4;
import 'package:zync_gum/features/home/domain/entities/business_entity/business_entity.dart'
    as _i8;
import 'package:zync_gum/features/home/domain/entities/inventory_entity/inventory_entity.dart'
    as _i7;
import 'package:zync_gum/features/home/domain/entities/production_line_entity/production_line_entity.dart'
    as _i6;
import 'package:zync_gum/features/home/domain/repositories/home_repositories.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HomeRepositories].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepositories extends _i1.Mock implements _i2.HomeRepositories {
  MockHomeRepositories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Either<_i5.Failure, List<_i6.ProductionLineEntity>>>
  watchProductionLines() =>
      (super.noSuchMethod(
            Invocation.method(#watchProductionLines, []),
            returnValue:
                _i3.Stream<
                  _i4.Either<_i5.Failure, List<_i6.ProductionLineEntity>>
                >.empty(),
          )
          as _i3.Stream<
            _i4.Either<_i5.Failure, List<_i6.ProductionLineEntity>>
          >);

  @override
  _i3.Stream<_i4.Either<_i5.Failure, List<_i7.InventoryEntity>>>
  watchInventory() =>
      (super.noSuchMethod(
            Invocation.method(#watchInventory, []),
            returnValue:
                _i3.Stream<
                  _i4.Either<_i5.Failure, List<_i7.InventoryEntity>>
                >.empty(),
          )
          as _i3.Stream<_i4.Either<_i5.Failure, List<_i7.InventoryEntity>>>);

  @override
  _i3.Stream<_i4.Either<_i5.Failure, List<_i8.BusinessEntity>>> watchBusinesses(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchBusinesses, [userId]),
            returnValue:
                _i3.Stream<
                  _i4.Either<_i5.Failure, List<_i8.BusinessEntity>>
                >.empty(),
          )
          as _i3.Stream<_i4.Either<_i5.Failure, List<_i8.BusinessEntity>>>);
}
