// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDjYoHC9cyfPOna5QR6RgdCl8AqrctPeg',
    appId: '1:403213553943:web:563086158fce1d615ea752',
    messagingSenderId: '403213553943',
    projectId: 'zync-gum',
    authDomain: 'zync-gum.firebaseapp.com',
    storageBucket: 'zync-gum.firebasestorage.app',
    measurementId: 'G-E2817SBE93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0529tT851Np1Bx3HAEZ3pSwSJe8MhLuA',
    appId: '1:403213553943:android:f07d8f56d6847c1a5ea752',
    messagingSenderId: '403213553943',
    projectId: 'zync-gum',
    storageBucket: 'zync-gum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT1SChOHEKGMwLR1Q-vctJ9KZNgC4p92k',
    appId: '1:403213553943:ios:ea6cafb4d71099f15ea752',
    messagingSenderId: '403213553943',
    projectId: 'zync-gum',
    storageBucket: 'zync-gum.firebasestorage.app',
    iosBundleId: 'com.example.zyncGum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT1SChOHEKGMwLR1Q-vctJ9KZNgC4p92k',
    appId: '1:403213553943:ios:ea6cafb4d71099f15ea752',
    messagingSenderId: '403213553943',
    projectId: 'zync-gum',
    storageBucket: 'zync-gum.firebasestorage.app',
    iosBundleId: 'com.example.zyncGum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDjYoHC9cyfPOna5QR6RgdCl8AqrctPeg',
    appId: '1:403213553943:web:e3729f769206b45e5ea752',
    messagingSenderId: '403213553943',
    projectId: 'zync-gum',
    authDomain: 'zync-gum.firebaseapp.com',
    storageBucket: 'zync-gum.firebasestorage.app',
    measurementId: 'G-LFCCLPM4BX',
  );
}
