// Mocks generated by Mockito 5.4.6 from annotations
// in zync_gum/test/helpers/integration_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:firebase_auth/firebase_auth.dart' as _i7;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i6;
import 'package:firebase_core/firebase_core.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:zync_gum/core/errors/failure.dart' as _i11;
import 'package:zync_gum/core/models/either/either.dart' as _i10;
import 'package:zync_gum/core/usecase/usecase.dart' as _i13;
import 'package:zync_gum/features/auth/domain/entities/auth_entity/auth_entity.dart'
    as _i12;
import 'package:zync_gum/features/auth/domain/repositories/auth_repositories.dart'
    as _i2;
import 'package:zync_gum/features/auth/domain/usecases/check_auth_usecase/check_auth_usecase.dart'
    as _i8;
import 'package:zync_gum/features/auth/domain/usecases/sign_in_email_usecase/sign_in_email_usecase.dart'
    as _i16;
import 'package:zync_gum/features/auth/domain/usecases/sign_in_google_usecase/sign_in_google_usecase.dart'
    as _i18;
import 'package:zync_gum/features/auth/domain/usecases/sign_out_usecase/sign_out_usecase.dart'
    as _i15;
import 'package:zync_gum/features/auth/domain/usecases/sign_up_email_usecase/sign_up_email_usecase.dart'
    as _i17;
import 'package:zync_gum/features/home/domain/entities/business_entity/business_entity.dart'
    as _i24;
import 'package:zync_gum/features/home/domain/entities/inventory_entity/inventory_entity.dart'
    as _i22;
import 'package:zync_gum/features/home/domain/entities/production_line_entity/production_line_entity.dart'
    as _i20;
import 'package:zync_gum/features/home/domain/repositories/home_repositories.dart'
    as _i3;
import 'package:zync_gum/features/home/domain/usecases/get_businesses_usecase/get_businesses_usecase.dart'
    as _i23;
import 'package:zync_gum/features/home/domain/usecases/get_inventory_usecase/get_inventory_usecase.dart'
    as _i21;
import 'package:zync_gum/features/home/domain/usecases/get_production_lines_usecase/get_production_lines_usecase.dart'
    as _i19;
import 'package:zync_gum/features/profile/domain/repositories/profile_repositories.dart'
    as _i4;
import 'package:zync_gum/features/profile/domain/usecases/get_user_profile_usecase/get_user_profile_usecase.dart'
    as _i25;
import 'package:zync_gum/features/profile/domain/usecases/update_avatar_url_usecase/update_avatar_url_usecase.dart'
    as _i27;
import 'package:zync_gum/features/profile/domain/usecases/update_user_name_usecase/update_user_name_usecase.dart'
    as _i26;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthRepositories_0 extends _i1.SmartFake
    implements _i2.AuthRepositories {
  _FakeAuthRepositories_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeRepositories_1 extends _i1.SmartFake
    implements _i3.HomeRepositories {
  _FakeHomeRepositories_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileRepositories_2 extends _i1.SmartFake
    implements _i4.ProfileRepositories {
  _FakeProfileRepositories_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_3 extends _i1.SmartFake implements _i5.FirebaseApp {
  _FakeFirebaseApp_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActionCodeInfo_4 extends _i1.SmartFake
    implements _i6.ActionCodeInfo {
  _FakeActionCodeInfo_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_5 extends _i1.SmartFake
    implements _i7.UserCredential {
  _FakeUserCredential_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_6 extends _i1.SmartFake
    implements _i7.ConfirmationResult {
  _FakeConfirmationResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserMetadata_7 extends _i1.SmartFake implements _i6.UserMetadata {
  _FakeUserMetadata_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiFactor_8 extends _i1.SmartFake implements _i7.MultiFactor {
  _FakeMultiFactor_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdTokenResult_9 extends _i1.SmartFake implements _i6.IdTokenResult {
  _FakeIdTokenResult_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_10 extends _i1.SmartFake implements _i7.User {
  _FakeUser_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CheckAuthUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckAuthUsecase extends _i1.Mock implements _i8.CheckAuthUsecase {
  MockCheckAuthUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity?>> call(
    _i13.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity?>>.value(
                  _i14.dummyValue<_i10.Either<_i11.Failure, _i12.UserEntity?>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity?>>);
}

/// A class which mocks [SignOutUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutUsecase extends _i1.Mock implements _i15.SignOutUsecase {
  MockSignOutUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i9.Future<_i10.Either<_i11.Failure, void>> call(_i13.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, void>>.value(
              _i14.dummyValue<_i10.Either<_i11.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, void>>);
}

/// A class which mocks [SignInEmailUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInEmailUsecase extends _i1.Mock
    implements _i16.SignInEmailUsecase {
  MockSignInEmailUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity>> call(
    _i16.SignInEmailParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity>>.value(
                  _i14.dummyValue<_i10.Either<_i11.Failure, _i12.UserEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity>>);
}

/// A class which mocks [SignUpEmailUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpEmailUsecase extends _i1.Mock
    implements _i17.SignUpEmailUsecase {
  MockSignUpEmailUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity>> call(
    _i17.SignUpEmailParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity>>.value(
                  _i14.dummyValue<_i10.Either<_i11.Failure, _i12.UserEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity>>);
}

/// A class which mocks [SignInGoogleUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInGoogleUsecase extends _i1.Mock
    implements _i18.SignInGoogleUsecase {
  MockSignInGoogleUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeAuthRepositories_0(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i2.AuthRepositories);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity>> call(
    _i13.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity>>.value(
                  _i14.dummyValue<_i10.Either<_i11.Failure, _i12.UserEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity>>);
}

/// A class which mocks [GetProductionLinesUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductionLinesUsecase extends _i1.Mock
    implements _i19.GetProductionLinesUsecase {
  MockGetProductionLinesUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.HomeRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeHomeRepositories_1(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i3.HomeRepositories);

  @override
  _i9.Stream<_i10.Either<_i11.Failure, List<_i20.ProductionLineEntity>>>
  call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i9.Stream<
                  _i10.Either<_i11.Failure, List<_i20.ProductionLineEntity>>
                >.empty(),
          )
          as _i9.Stream<
            _i10.Either<_i11.Failure, List<_i20.ProductionLineEntity>>
          >);
}

/// A class which mocks [GetInventoryUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetInventoryUsecase extends _i1.Mock
    implements _i21.GetInventoryUsecase {
  MockGetInventoryUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.HomeRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeHomeRepositories_1(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i3.HomeRepositories);

  @override
  _i9.Stream<_i10.Either<_i11.Failure, List<_i22.InventoryEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i9.Stream<
                  _i10.Either<_i11.Failure, List<_i22.InventoryEntity>>
                >.empty(),
          )
          as _i9.Stream<_i10.Either<_i11.Failure, List<_i22.InventoryEntity>>>);
}

/// A class which mocks [GetBusinessesUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBusinessesUsecase extends _i1.Mock
    implements _i23.GetBusinessesUsecase {
  MockGetBusinessesUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.HomeRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeHomeRepositories_1(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i3.HomeRepositories);

  @override
  _i9.Stream<_i10.Either<_i11.Failure, List<_i24.BusinessEntity>>> call(
    _i23.GetBusinessesParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i9.Stream<
                  _i10.Either<_i11.Failure, List<_i24.BusinessEntity>>
                >.empty(),
          )
          as _i9.Stream<_i10.Either<_i11.Failure, List<_i24.BusinessEntity>>>);
}

/// A class which mocks [GetUserProfileUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserProfileUsecase extends _i1.Mock
    implements _i25.GetUserProfileUsecase {
  MockGetUserProfileUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ProfileRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeProfileRepositories_2(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i4.ProfileRepositories);

  @override
  _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity>> call(
    _i25.GetUserProfileParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity>>.value(
                  _i14.dummyValue<_i10.Either<_i11.Failure, _i12.UserEntity>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, _i12.UserEntity>>);
}

/// A class which mocks [UpdateUserNameUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserNameUsecase extends _i1.Mock
    implements _i26.UpdateUserNameUsecase {
  MockUpdateUserNameUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ProfileRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeProfileRepositories_2(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i4.ProfileRepositories);

  @override
  _i9.Future<_i10.Either<_i11.Failure, void>> call(
    _i26.UpdateUserNameParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, void>>.value(
              _i14.dummyValue<_i10.Either<_i11.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, void>>);
}

/// A class which mocks [UpdateAvatarUrlUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateAvatarUrlUsecase extends _i1.Mock
    implements _i27.UpdateAvatarUrlUsecase {
  MockUpdateAvatarUrlUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ProfileRepositories get repositories =>
      (super.noSuchMethod(
            Invocation.getter(#repositories),
            returnValue: _FakeProfileRepositories_2(
              this,
              Invocation.getter(#repositories),
            ),
          )
          as _i4.ProfileRepositories);

  @override
  _i9.Future<_i10.Either<_i11.Failure, void>> call(
    _i27.UpdateAvatarUrlParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i9.Future<_i10.Either<_i11.Failure, void>>.value(
              _i14.dummyValue<_i10.Either<_i11.Failure, void>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i9.Future<_i10.Either<_i11.Failure, void>>);
}

/// A class which mocks [FirebaseAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuth extends _i1.Mock implements _i7.FirebaseAuth {
  MockFirebaseAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_3(this, Invocation.getter(#app)),
          )
          as _i5.FirebaseApp);

  @override
  set app(_i5.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  set tenantId(String? tenantId) => super.noSuchMethod(
    Invocation.setter(#tenantId, tenantId),
    returnValueForMissingStub: null,
  );

  @override
  set customAuthDomain(String? customAuthDomain) => super.noSuchMethod(
    Invocation.setter(#customAuthDomain, customAuthDomain),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i9.Future<void> useAuthEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #useAuthEmulator,
              [host, port],
              {#automaticHostMapping: automaticHostMapping},
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> applyActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#applyActionCode, [code]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i6.ActionCodeInfo> checkActionCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#checkActionCode, [code]),
            returnValue: _i9.Future<_i6.ActionCodeInfo>.value(
              _FakeActionCodeInfo_4(
                this,
                Invocation.method(#checkActionCode, [code]),
              ),
            ),
          )
          as _i9.Future<_i6.ActionCodeInfo>);

  @override
  _i9.Future<void> confirmPasswordReset({
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPasswordReset, [], {
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.UserCredential> createUserWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<List<String>> fetchSignInMethodsForEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSignInMethodsForEmail, [email]),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<_i7.UserCredential> getRedirectResult() =>
      (super.noSuchMethod(
            Invocation.method(#getRedirectResult, []),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#getRedirectResult, []),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  bool isSignInWithEmailLink(String? emailLink) =>
      (super.noSuchMethod(
            Invocation.method(#isSignInWithEmailLink, [emailLink]),
            returnValue: false,
          )
          as bool);

  @override
  _i9.Stream<_i7.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i9.Stream<_i7.User?>.empty(),
          )
          as _i9.Stream<_i7.User?>);

  @override
  _i9.Stream<_i7.User?> idTokenChanges() =>
      (super.noSuchMethod(
            Invocation.method(#idTokenChanges, []),
            returnValue: _i9.Stream<_i7.User?>.empty(),
          )
          as _i9.Stream<_i7.User?>);

  @override
  _i9.Stream<_i7.User?> userChanges() =>
      (super.noSuchMethod(
            Invocation.method(#userChanges, []),
            returnValue: _i9.Stream<_i7.User?>.empty(),
          )
          as _i9.Stream<_i7.User?>);

  @override
  _i9.Future<void> sendPasswordResetEmail({
    required String? email,
    _i6.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> sendSignInLinkToEmail({
    required String? email,
    required _i6.ActionCodeSettings? actionCodeSettings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendSignInLinkToEmail, [], {
              #email: email,
              #actionCodeSettings: actionCodeSettings,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setLanguageCode(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguageCode, [languageCode]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setSettings({
    bool? appVerificationDisabledForTesting = false,
    String? userAccessGroup,
    String? phoneNumber,
    String? smsCode,
    bool? forceRecaptchaFlow,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setSettings, [], {
              #appVerificationDisabledForTesting:
                  appVerificationDisabledForTesting,
              #userAccessGroup: userAccessGroup,
              #phoneNumber: phoneNumber,
              #smsCode: smsCode,
              #forceRecaptchaFlow: forceRecaptchaFlow,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setPersistence(_i6.Persistence? persistence) =>
      (super.noSuchMethod(
            Invocation.method(#setPersistence, [persistence]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.UserCredential> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#signInAnonymously, []),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> signInWithCredential(
    _i6.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCredential, [credential]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#signInWithCredential, [credential]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> signInWithCustomToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithCustomToken, [token]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#signInWithCustomToken, [token]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#signInWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> signInWithEmailLink({
    required String? email,
    required String? emailLink,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailLink, [], {
              #email: email,
              #emailLink: emailLink,
            }),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#signInWithEmailLink, [], {
                  #email: email,
                  #emailLink: emailLink,
                }),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> signInWithProvider(
    _i6.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithProvider, [provider]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#signInWithProvider, [provider]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.ConfirmationResult> signInWithPhoneNumber(
    String? phoneNumber, [
    _i7.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i9.Future<_i7.ConfirmationResult>.value(
              _FakeConfirmationResult_6(
                this,
                Invocation.method(#signInWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.ConfirmationResult>);

  @override
  _i9.Future<_i7.UserCredential> signInWithPopup(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPopup, [provider]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#signInWithPopup, [provider]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<void> signInWithRedirect(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithRedirect, [provider]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String> verifyPasswordResetCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPasswordResetCode, [code]),
            returnValue: _i9.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#verifyPasswordResetCode, [code]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> verifyPhoneNumber({
    String? phoneNumber,
    _i6.PhoneMultiFactorInfo? multiFactorInfo,
    required _i6.PhoneVerificationCompleted? verificationCompleted,
    required _i6.PhoneVerificationFailed? verificationFailed,
    required _i6.PhoneCodeSent? codeSent,
    required _i6.PhoneCodeAutoRetrievalTimeout? codeAutoRetrievalTimeout,
    String? autoRetrievedSmsCodeForTesting,
    Duration? timeout = const Duration(seconds: 30),
    int? forceResendingToken,
    _i6.MultiFactorSession? multiFactorSession,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneNumber, [], {
              #phoneNumber: phoneNumber,
              #multiFactorInfo: multiFactorInfo,
              #verificationCompleted: verificationCompleted,
              #verificationFailed: verificationFailed,
              #codeSent: codeSent,
              #codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
              #autoRetrievedSmsCodeForTesting: autoRetrievedSmsCodeForTesting,
              #timeout: timeout,
              #forceResendingToken: forceResendingToken,
              #multiFactorSession: multiFactorSession,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> revokeTokenWithAuthorizationCode(
    String? authorizationCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#revokeTokenWithAuthorizationCode, [
              authorizationCode,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> initializeRecaptchaConfig() =>
      (super.noSuchMethod(
            Invocation.method(#initializeRecaptchaConfig, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i7.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get emailVerified =>
      (super.noSuchMethod(Invocation.getter(#emailVerified), returnValue: false)
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(Invocation.getter(#isAnonymous), returnValue: false)
          as bool);

  @override
  _i6.UserMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeUserMetadata_7(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i6.UserMetadata);

  @override
  List<_i6.UserInfo> get providerData =>
      (super.noSuchMethod(
            Invocation.getter(#providerData),
            returnValue: <_i6.UserInfo>[],
          )
          as List<_i6.UserInfo>);

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i14.dummyValue<String>(this, Invocation.getter(#uid)),
          )
          as String);

  @override
  _i7.MultiFactor get multiFactor =>
      (super.noSuchMethod(
            Invocation.getter(#multiFactor),
            returnValue: _FakeMultiFactor_8(
              this,
              Invocation.getter(#multiFactor),
            ),
          )
          as _i7.MultiFactor);

  @override
  _i9.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [forceRefresh]),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<_i6.IdTokenResult> getIdTokenResult([
    bool? forceRefresh = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdTokenResult, [forceRefresh]),
            returnValue: _i9.Future<_i6.IdTokenResult>.value(
              _FakeIdTokenResult_9(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
          )
          as _i9.Future<_i6.IdTokenResult>);

  @override
  _i9.Future<_i7.UserCredential> linkWithCredential(
    _i6.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithCredential, [credential]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> linkWithProvider(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithProvider, [provider]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> reauthenticateWithProvider(
    _i6.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithProvider, [provider]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<_i7.UserCredential> reauthenticateWithPopup(
    _i6.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPopup, [provider]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<void> reauthenticateWithRedirect(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithRedirect, [provider]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.UserCredential> linkWithPopup(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPopup, [provider]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<void> linkWithRedirect(_i6.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithRedirect, [provider]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i7.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i9.Future<_i7.ConfirmationResult>.value(
              _FakeConfirmationResult_6(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i9.Future<_i7.ConfirmationResult>);

  @override
  _i9.Future<_i7.UserCredential> reauthenticateWithCredential(
    _i6.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i9.Future<_i7.UserCredential>.value(
              _FakeUserCredential_5(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
          )
          as _i9.Future<_i7.UserCredential>);

  @override
  _i9.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> sendEmailVerification([
    _i6.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [actionCodeSettings]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.User> unlink(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#unlink, [providerId]),
            returnValue: _i9.Future<_i7.User>.value(
              _FakeUser_10(this, Invocation.method(#unlink, [providerId])),
            ),
          )
          as _i9.Future<_i7.User>);

  @override
  _i9.Future<void> updateEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmail, [newEmail]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updatePhoneNumber(
    _i6.PhoneAuthCredential? phoneCredential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [phoneCredential]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updatePhotoURL(String? photoURL) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoURL, [photoURL]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i6.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBeforeUpdateEmail, [
              newEmail,
              actionCodeSettings,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}
