// Mocks generated by Mockito 5.4.6 from annotations
// in zync_gum/test/features/auth/domain/usecases/sign_out_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:zync_gum/core/errors/failure.dart' as _i5;
import 'package:zync_gum/core/models/either/either.dart' as _i4;
import 'package:zync_gum/features/auth/domain/entities/auth_entity/auth_entity.dart'
    as _i6;
import 'package:zync_gum/features/auth/domain/repositories/auth_repositories.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepositories].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepositories extends _i1.Mock implements _i2.AuthRepositories {
  MockAuthRepositories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserEntity>>(
                    this,
                    Invocation.method(#signInWithEmail, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>> signUpWithEmail({
    required String? email,
    required String? password,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [], {
              #email: email,
              #password: password,
              #name: name,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserEntity>>(
                    this,
                    Invocation.method(#signUpWithEmail, [], {
                      #email: email,
                      #password: password,
                      #name: name,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserEntity>>(
                    this,
                    Invocation.method(#signInWithGoogle, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity?>> getAuthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthStatus, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity?>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserEntity?>>(
                    this,
                    Invocation.method(#getAuthStatus, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity?>>);
}
